name: mu3e_trigger
description: Environment for Mu3e Trigger project
version: 0.1.0

channels:
  - conda-forge

# it is strongly recommended to specify versions of packages installed through conda
# to avoid situation when version-unspecified packages install their latest major
# versions which can sometimes break things

# current approach below keeps the dependencies in the same major versions across all
# users, but allows for different minor and patch versions of packages where backwards
# compatibility is usually guaranteed

dependencies:
  - python=3.10
  - keras
  - numpy
  - pandas
  - scikit-learn
  - scikit-image
  - matplotlib
  - pytorch
  - hydra-core
  - omegaconf
  - ipykernel
  - tensorflow
  - pydot